version: '3.9'
services:
  postgres:
    image: 'postgres:14.5'    
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: db # The PostgreSQL default database (automatically created at first launch)
    env_file:
      - ./server/config.env # configure postgres
    volumes:
      - postgres:/var/lib/postgresql/data # persist data even if container shuts down
    networks:
      - test-network
  
  postgres-seed:
    build:
      context: ./server
      dockerfile: ./postgres-seed/Dockerfile
    depends_on:
      - postgres
    networks:
      - test-network

  pgadmin:
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - test-network

  server:
    restart: on-failure
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - postgres-seed
    networks:
      - test-network
  
  client:
    restart: on-failure
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    networks:
      - test-network

volumes:
    postgres:
    pgadmin:

networks:
  test-network:
    name: test-network
    driver: bridge